### ISSUE TITLE
[Question] Is this folder structure encouraged for React Native project as well?

### ISSUE THREAD

**Issue by bijaykumarpun** [ahsan-chy/React-JS-Advance-Folder-Structure#1]
Somewhat new to React/ReactJS/RN, so was wondering if this folder structure is applicable for RN projects as well?
Many thanks!

**Comment by bijaykumarpun** [comment]
cc: @ahsan-chy

**Comment by ahsan-chy** [comment]
@bijaykumarpun you should follow basic RN structure and can embed these practices there, like utils, components, env, apiServices etc.

**Comment by bijaykumarpun** [comment]
Thanks for the reply @ahsan-chy !
